### PR TITLE
Adding compute_features.py.

### PR DESCRIPTION
**Pull request by Heringer-Epson**
This code calculates the pEW, velocity and depth of given spectral features. The procedures are similar to those described in http://adsabs.harvard.edu/abs/2012MNRAS.425.1819S .

### CODE REVIEW

**Comment by Heringer-Epson** [comment]
Most definitely. I will make a new pull request once a add that. One
question: one of the routines requires a package (PyAstronomy) to compute
extinction - how should I go about this? Should I simply add a comment
saying that one needs to install PyAstronomy in the same conda env that is
running tardis?

**Comment by unoebauer** [comment]
Yes, you could do that. Otherwise you could provide a conda requirements file similar to that of Tardis. I am not sure if this is very practical. Since the conda env should be able to run tardis, the file would have to be kept in sync with the one of the main tardis repository. Maybe simpler to just point out in the documentation that PyAstronomy has be installed in addition.

**Comment by Heringer-Epson** [comment]
Sorry for the delay. Documentation has been added following the example of
the other packages.

**Comment by unoebauer** [comment]
This is obsolete now, right?

**Comment by Heringer-Epson** [comment]
Shouldn't be, why? Unless there is another package to get pEW, velocities,
etc? Or you mean that it wouldn't work with newer versions of tardis?

**Comment by unoebauer** [comment]
Because you included ``compute_feature.py`` in PR #16 which I've already merged.

**Comment by Heringer-Epson** [comment]
Nvm, I just saw you accepted to merge the most recent request, so yes, the
old request is obsolete. Sorry for the confusion =)

**Pull request closed without merging**
